stages:
  - Install SAM
  - Release

cache:
  paths:
    - node_modules/

stage1:
  stage: Install SAM
  image: python:3.8
  before_script:
    - pip3 install awscli --upgrade
    - pip3 install aws-sam-cli --upgrade

npm_build:
  stage: Release
  image: "node:lts"
  before_script:
    - npm install
  script:
    - npm run release
