stages:
  - Install SAM
  - Release

# cache:
#   paths:
#     - node_modules/

production:
  stage: Install SAM
  image: python:3.8
  before_script:
    - pip3 install awscli --upgrade
    - pip3 install aws-sam-cli --upgrade

npm_build:
  stage: Release
  image: "node:lts"
  before_script:
    - npm install
  script:
    - npm run release
 image: python:3.8

 stages:
   - deploy

 production:
   stage: deploy
   before_script:
     - pip3 install awscli --upgrade
     - pip3 install aws-sam-cli --upgrade
   script:
    - cd sam 
    - sam build
    - sam package --output-template-file template.yaml --s3-bucket demo-sam-deploy-1
    - sam deploy --template-file template.yaml --stack-name gitlab-example --s3-bucket demo-sam-deploy-1 --capabilities CAPABILITY_IAM --region ap-south-1
  environment: production
