# Node Image for docker on which code will execute
image: node:latest

# This is the stages / task to perfom in jobs
stages:
  - nodeBuild
  - deploy 

build_node:
  stage: nodeBuild
  script:
    - cd sam
    - npm install
    - cd ..

deploy_master:
  stage: deploy
  image: python:latest
  
  before_script:
    - pip3 install awscli --upgrade
    - pip3 install aws-sam-cli --upgrade
  script:
    - cd sam 
   # - sam build
    - sam package --output-template-file template.yaml --s3-bucket demo-sam-deploy-1
    - sam deploy --template-file template.yaml --stack-name gitlab-example --s3-bucket demo-sam-deploy-1 --capabilities CAPABILITY_IAM --region ap-south-1
  environment: production
  only: ["development"]