# Node Image for docker on which code will execute
image: python:3.8

# This is the stages / task to perfom in jobs
stages:
  #- build
  # - lint
  - deploy

# Job One for making build
#build_master:
 # stage: build
 # image: "node:lts"
#  before_script:
 #   - npm install
#  script:
#    - npm run release

 # only: ["development"]
  
deploy_master:
  image: python:latest
  stage: deploy
  before_script:
    - pip3 install awscli --upgrade
    - pip3 install aws-sam-cli --upgrade
  script:
    - cd sam 
    - sam build
    - sam package --output-template-file template.yaml --s3-bucket demo-sam-deploy-1
    - sam deploy --template-file template.yaml --stack-name gitlab-example --s3-bucket demo-sam-deploy-1 --capabilities CAPABILITY_IAM --region ap-south-1
  environment: production
  only: ["development"]