AWSTemplateFormatVersion: 2010-09-09
Description: >-
  nta-master

Transform:
  - AWS::Serverless-2016-10-31

Globals:
  Api:
    EndpointConfiguration: REGIONAL
    Cors:
      AllowHeaders: "'Content-Type, Authorization, nta-authority-id, username, access-token'"
      AllowMethods: "'POST,GET,PATCH,PUT,DELETE'"
      AllowOrigin: "'*'"

  Function:
    Runtime: nodejs12.x
    MemorySize: 128
    Timeout: 100

Resources:
  GlobalsApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod

  GatewayResponseDefault4XX:
    Type: AWS::ApiGateway::GatewayResponse
    Properties:
      ResponseParameters:
        gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
        gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type, Authorization'"
        gatewayresponse.header.Access-Control-Allow-Methods: "'POST,GET,PATCH,PUT,DELETE'"
      ResponseType: DEFAULT_4XX
      RestApiId: !Ref NtaApi

  # # NTA Section
  CreateInstituteTypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.createInstituteTypeHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/type
            Method: POST
            RestApiId: !Ref GlobalsApi

  CreateAddressTextFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.createInstituteTypeHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/type
            Method: POST
            RestApiId: !Ref GlobalsApi

  CreatePhoneTextFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.createInstituteTypeHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/type
            Method: POST
            RestApiId: !Ref GlobalsApi

  CreatePhoneAssociatedPostFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.createInstituteTypeHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/type
            Method: POST
            RestApiId: !Ref GlobalsApi

  CreatePhoneTypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.createInstituteTypeHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/type
            Method: POST
            RestApiId: !Ref GlobalsApi

  CreateEmailTextFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.createInstituteTypeHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/type
            Method: POST
            RestApiId: !Ref GlobalsApi

  CreateEmailAssociatedPostFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.createInstituteTypeHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/type
            Method: POST
            RestApiId: !Ref GlobalsApi

  CreateEmailTypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.createInstituteTypeHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/type
            Method: POST
            RestApiId: !Ref GlobalsApi

  CreateSocialMediaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.createInstituteTypeHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/type
            Method: POST
            RestApiId: !Ref GlobalsApi

  CreateRegistrationTypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.createInstituteTypeHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/type
            Method: POST
            RestApiId: !Ref GlobalsApi

  CreateRegistrationDocumentTypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.createInstituteTypeHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/type
            Method: POST
            RestApiId: !Ref GlobalsApi

  CreateInstitutionAffiliationGradeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.createInstituteTypeHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/type
            Method: POST
            RestApiId: !Ref GlobalsApi

  CreateInstitutionAffiliationStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.createInstituteTypeHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/type
            Method: POST
            RestApiId: !Ref GlobalsApi

  CreateInstitutionAffiliationTypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.createInstituteTypeHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/type
            Method: POST
            RestApiId: !Ref GlobalsApi

  CreateInstitutionAffiliationAuthorityFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.createInstituteTypeHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/type
            Method: POST
            RestApiId: !Ref GlobalsApi

  ListInstituteTypeListFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.createInstituteTypeHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/type
            Method: POST
            RestApiId: !Ref GlobalsApi

  ListAddressTextListFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.createInstituteTypeHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/type
            Method: POST
            RestApiId: !Ref GlobalsApi

  ListPhoneTextListFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.createInstituteTypeHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/type
            Method: POST
            RestApiId: !Ref GlobalsApi

  ListPhoneAssociatedPostListFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.createInstituteTypeHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/type
            Method: POST
            RestApiId: !Ref GlobalsApi

  ListPhoneTypeListFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.createInstituteTypeHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/type
            Method: POST
            RestApiId: !Ref GlobalsApi

  ListEmailTextListFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.createInstituteTypeHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/type
            Method: POST
            RestApiId: !Ref GlobalsApi

  ListEmailAssociatedPostListFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.createInstituteTypeHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/type
            Method: POST
            RestApiId: !Ref GlobalsApi

  ListEmailTypeListFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.createInstituteTypeHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/type
            Method: POST
            RestApiId: !Ref GlobalsApi

  ListSocialMediaListFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.createInstituteTypeHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/type
            Method: POST
            RestApiId: !Ref GlobalsApi

  ListRegistrationTypeListFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.createInstituteTypeHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/type
            Method: POST
            RestApiId: !Ref GlobalsApi

  ListRegistrationDocumentTypeListFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.createInstituteTypeHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/type
            Method: POST
            RestApiId: !Ref GlobalsApi

  ListInstitutionAffiliationGradeListFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.createInstituteTypeHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/type
            Method: POST
            RestApiId: !Ref GlobalsApi

  ListInstitutionAffiliationStatusListFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.createInstituteTypeHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/type
            Method: POST
            RestApiId: !Ref GlobalsApi

  ListInstitutionAffiliationTypeListFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.createInstituteTypeHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/type
            Method: POST
            RestApiId: !Ref GlobalsApi

  ListInstitutionAffiliationAuthorityListFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.createInstituteTypeHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/type
            Method: POST
            RestApiId: !Ref GlobalsApi
