AWSTemplateFormatVersion: 2010-09-09
Description: >-
  nta-master

Transform:
  - AWS::Serverless-2016-10-31

Globals:
  Api:
    EndpointConfiguration: REGIONAL
    Cors:
      AllowHeaders: "'Content-Type, Authorization, nta-authority-id, username, access-token'"
      AllowMethods: "'POST,GET,PATCH,PUT,DELETE'"
      AllowOrigin: "'*'"

  Function:
    Runtime: nodejs12.x
    MemorySize: 128
    Timeout: 100

Resources:
  GlobalsApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod

  GatewayResponseDefault4XX:
    Type: AWS::ApiGateway::GatewayResponse
    Properties:
      ResponseParameters:
        gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
        gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type, Authorization'"
        gatewayresponse.header.Access-Control-Allow-Methods: "'POST,GET,PATCH,PUT,DELETE'"
      ResponseType: DEFAULT_4XX
      RestApiId: !Ref NtaApi

  # # NTA Section
  CreateInstituteTypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.createInstituteTypeHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/type
            Method: POST
            RestApiId: !Ref GlobalsApi

  CreateAddressTextFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.createAddressTextHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/address/text
            Method: POST
            RestApiId: !Ref GlobalsApi

  CreatePhoneTextFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.createPhoneTextHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/phone/text
            Method: POST
            RestApiId: !Ref GlobalsApi

  CreatePhoneAssociatedPostFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.createPhoneAssociatedPostHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/phone/associated-post
            Method: POST
            RestApiId: !Ref GlobalsApi

  CreatePhoneTypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.createPhoneTypeHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/phone/type
            Method: POST
            RestApiId: !Ref GlobalsApi

  CreateEmailTextFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.createEmailTextHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/email/text
            Method: POST
            RestApiId: !Ref GlobalsApi

  CreateEmailAssociatedPostFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.createEmailAssociatedPostHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/email/associated-post
            Method: POST
            RestApiId: !Ref GlobalsApi

  CreateEmailTypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.createEmailTypeHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/email/type
            Method: POST
            RestApiId: !Ref GlobalsApi

  CreateSocialMediaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.createSocialMediaHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/social-media
            Method: POST
            RestApiId: !Ref GlobalsApi

  CreateRegistrationTypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.createRegistrationTypeHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/registration/type
            Method: POST
            RestApiId: !Ref GlobalsApi

  CreateRegistrationDocumentTypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.createRegistrationDocumentTypeHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/registration/document
            Method: POST
            RestApiId: !Ref GlobalsApi

  CreateInstitutionAffiliationGradeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.createInstitutionAffiliationGradeHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/affiliation/grade
            Method: POST
            RestApiId: !Ref GlobalsApi

  CreateInstitutionAffiliationStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.createInstitutionAffiliationStatusHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/affiliation/status
            Method: POST
            RestApiId: !Ref GlobalsApi

  CreateInstitutionAffiliationTypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.createInstitutionAffiliationTypeHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/affiliation/type
            Method: POST
            RestApiId: !Ref GlobalsApi

  CreateInstitutionAffiliationAuthorityFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.createInstitutionAffiliationAuthorityHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/affiliation/authority
            Method: POST
            RestApiId: !Ref GlobalsApi

  ListInstituteTypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.listInstituteTypeHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/type
            Method: POST
            RestApiId: !Ref GlobalsApi

  ListAddressTextFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.listAddressTextHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/type
            Method: POST
            RestApiId: !Ref GlobalsApi

  ListPhoneTextFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.listPhoneTextHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/type
            Method: POST
            RestApiId: !Ref GlobalsApi

  ListPhoneAssociatedPostFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.listPhoneAssociatedPostHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/type
            Method: POST
            RestApiId: !Ref GlobalsApi

  ListPhoneTypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.listPhoneTypeHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/type
            Method: POST
            RestApiId: !Ref GlobalsApi

  ListEmailTextFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.listEmailTextHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/type
            Method: POST
            RestApiId: !Ref GlobalsApi

  ListEmailAssociatedPostFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.listEmailAssociatedPostHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/type
            Method: POST
            RestApiId: !Ref GlobalsApi

  ListEmailTypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.listEmailTypeHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/type
            Method: POST
            RestApiId: !Ref GlobalsApi

  ListSocialMediaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.listSocialMediaHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/type
            Method: POST
            RestApiId: !Ref GlobalsApi

  ListRegistrationTypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.listRegistrationTypeHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/type
            Method: POST
            RestApiId: !Ref GlobalsApi

  ListRegistrationDocumentTypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.listRegistrationDocumentTypeHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/type
            Method: POST
            RestApiId: !Ref GlobalsApi

  ListInstitutionAffiliationGradeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.listInstitutionAffiliationGradeHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/type
            Method: POST
            RestApiId: !Ref GlobalsApi

  ListInstitutionAffiliationStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.listInstitutionAffiliationStatusHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/type
            Method: POST
            RestApiId: !Ref GlobalsApi

  ListInstitutionAffiliationTypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.listInstitutionAffiliationTypeHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/type
            Method: POST
            RestApiId: !Ref GlobalsApi

  ListInstitutionAffiliationAuthorityFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-global.listInstitutionAffiliationAuthorityHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '*'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /masters/institute/type
            Method: POST
            RestApiId: !Ref GlobalsApi

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${GlobalsApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"