AWSTemplateFormatVersion: 2010-09-09
Description: >-
  nta-master

Transform:
  - AWS::Serverless-2016-10-31

Resources:
  NTADomain:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./nta-domain.yml

  DynamoDBTables:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./nta-tables.yml

  NTAGlobal:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./nta-global.yml

  NTAAuthority:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./nta-authority.yml

  NTAInstitute:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./nta-institute.yml

  NTAStudent:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./nta-student.yml
