AWSTemplateFormatVersion: 2010-09-09
Description: >-
  nta-master

Transform:
  - AWS::Serverless-2016-10-31

Globals:
  Api:
    EndpointConfiguration: REGIONAL
    Cors:
      AllowHeaders: "'Content-Type, Authorization, nta-authority-id, username, access-token'"
      AllowMethods: "'POST,GET,PATCH,PUT,DELETE'"
      AllowOrigin: "'*'"

  Function:
    Runtime: nodejs12.x
    MemorySize: 128
    Timeout: 100
    Environment:
      Variables:
        INSTITUTE_TABLE: !Ref InstituteTable

Resources:
  GatewayResponseDefault4XX:
    Type: "AWS::ApiGateway::GatewayResponse"
    Properties:
      ResponseParameters:
        gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
        gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type, Authorization'"
        gatewayresponse.header.Access-Control-Allow-Methods: "'POST,GET,PATCH,PUT,DELETE'"
      ResponseType: DEFAULT_4XX
      RestApiId:
        Ref: "ServerlessRestApi"

  # NTA Section
  CreateNTAAuthorityFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-institute.createNTAAuthorityHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "*"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /NTA
            Method: POST
          Auth:
            DefaultAuthorizer: InstituteCognitoAuthorizer
            Authorizers:
              InstituteCognitoAuthorizer:
                UserPoolArn: arn:aws:cognito-idp:ap-south-1:725755216375:userpool/ap-south-1_qhEXlobaj

  ListNTAAuthorityFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-institute.listNTAAuthorityHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "*"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /NTA/authority
            Method: GET
          Auth:
            DefaultAuthorizer: InstituteCognitoAuthorizer
            Authorizers:
              InstituteCognitoAuthorizer:
                UserPoolArn: arn:aws:cognito-idp:ap-south-1:725755216375:userpool/ap-south-1_qhEXlobaj

  CreateNTAUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-institute.createNTAUserHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "*"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /NTA/user
            Method: POST
          Auth:
            DefaultAuthorizer: InstituteCognitoAuthorizer
            Authorizers:
              InstituteCognitoAuthorizer:
                UserPoolArn: arn:aws:cognito-idp:ap-south-1:725755216375:userpool/ap-south-1_qhEXlobaj

  deleteNTAUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-institute.deleteNTAUserHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "*"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /NTA/user/{mobile}
            Method: DELETE
          Auth:
            DefaultAuthorizer: InstituteCognitoAuthorizer
            Authorizers:
              InstituteCognitoAuthorizer:
                UserPoolArn: arn:aws:cognito-idp:ap-south-1:725755216375:userpool/ap-south-1_qhEXlobaj

  CheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-institute.checkTokenHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "*"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /NTA/user/check
            Method: GET
          Auth:
            DefaultAuthorizer: InstituteCognitoAuthorizer
            Authorizers:
              InstituteCognitoAuthorizer:
                UserPoolArn: arn:aws:cognito-idp:ap-south-1:725755216375:userpool/ap-south-1_qhEXlobaj

  SetNTAPassword:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-institute.newPasswordChallengeHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "*"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /NTA/user/challenge
            Method: POST
          Auth:
            DefaultAuthorizer: InstituteCognitoAuthorizer
            Authorizers:
              InstituteCognitoAuthorizer:
                UserPoolArn: arn:aws:cognito-idp:ap-south-1:725755216375:userpool/ap-south-1_qhEXlobaj

  # Create NTA Masters
  CreateFeesHead:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-institute.createFeesHeadHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "*"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /NTA/masters/fees/head
            Method: POST
          Auth:
            DefaultAuthorizer: InstituteCognitoAuthorizer
            Authorizers:
              InstituteCognitoAuthorizer:
                UserPoolArn: arn:aws:cognito-idp:ap-south-1:725755216375:userpool/ap-south-1_qhEXlobaj

  CreateAccountHead:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-institute.createAccountHeadHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "*"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /NTA/masters/accounts/head
            Method: POST
          Auth:
            DefaultAuthorizer: InstituteCognitoAuthorizer
            Authorizers:
              InstituteCognitoAuthorizer:
                UserPoolArn: arn:aws:cognito-idp:ap-south-1:725755216375:userpool/ap-south-1_qhEXlobaj

  CreateFeesType:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-institute.createFeeTypeHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "*"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /NTA/masters/fees/type
            Method: POST
          Auth:
            DefaultAuthorizer: InstituteCognitoAuthorizer
            Authorizers:
              InstituteCognitoAuthorizer:
                UserPoolArn: arn:aws:cognito-idp:ap-south-1:725755216375:userpool/ap-south-1_qhEXlobaj

  # List NTA Masters
  ListFeesHead:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-institute.getFeesHeadListHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "*"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /NTA/masters/fees/head
            Method: GET
          Auth:
            DefaultAuthorizer: InstituteCognitoAuthorizer
            Authorizers:
              InstituteCognitoAuthorizer:
                UserPoolArn: arn:aws:cognito-idp:ap-south-1:725755216375:userpool/ap-south-1_qhEXlobaj

  GetFeesHeadByIDFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-institute.getFeesHeadMasterByIdHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "*"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /NTA/masters/fees/head/{id}
            Method: GET
          Auth:
            DefaultAuthorizer: InstituteCognitoAuthorizer
            Authorizers:
              InstituteCognitoAuthorizer:
                UserPoolArn: arn:aws:cognito-idp:ap-south-1:725755216375:userpool/ap-south-1_qhEXlobaj

  ListAccountsHead:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-institute.getAccountHeadListHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "*"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /NTA/masters/accounts/head
            Method: GET
          Auth:
            DefaultAuthorizer: InstituteCognitoAuthorizer
            Authorizers:
              InstituteCognitoAuthorizer:
                UserPoolArn: arn:aws:cognito-idp:ap-south-1:725755216375:userpool/ap-south-1_qhEXlobaj

  ListFeesType:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-institute.getFeeTypeListHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "*"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /NTA/masters/fees/type
            Method: GET
          Auth:
            DefaultAuthorizer: InstituteCognitoAuthorizer
            Authorizers:
              InstituteCognitoAuthorizer:
                UserPoolArn: arn:aws:cognito-idp:ap-south-1:725755216375:userpool/ap-south-1_qhEXlobaj

  # Edit NTA Masters
  EditFeesHead:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-institute.editFeesHeadHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "*"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /NTA/masters/fees/head/{id}
            Method: POST
          Auth:
            DefaultAuthorizer: InstituteCognitoAuthorizer
            Authorizers:
              InstituteCognitoAuthorizer:
                UserPoolArn: arn:aws:cognito-idp:ap-south-1:725755216375:userpool/ap-south-1_qhEXlobaj

  EditFeesType:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-institute.editFeesTypeHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "*"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /NTA/masters/fees/type/{id}
            Method: POST
          Auth:
            DefaultAuthorizer: InstituteCognitoAuthorizer
            Authorizers:
              InstituteCognitoAuthorizer:
                UserPoolArn: arn:aws:cognito-idp:ap-south-1:725755216375:userpool/ap-south-1_qhEXlobaj

  EditAccountsHead:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-institute.editAccountsHeadHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "*"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /NTA/masters/accounts/head/{id}
            Method: POST
          Auth:
            DefaultAuthorizer: InstituteCognitoAuthorizer
            Authorizers:
              InstituteCognitoAuthorizer:
                UserPoolArn: arn:aws:cognito-idp:ap-south-1:725755216375:userpool/ap-south-1_qhEXlobaj

  # Delete NTA Masters
  DeleteFeesHead:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-institute.deleteFeesHeadHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "*"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /NTA/masters/fees/head/{id}
            Method: DELETE
          Auth:
            DefaultAuthorizer: InstituteCognitoAuthorizer
            Authorizers:
              InstituteCognitoAuthorizer:
                UserPoolArn: arn:aws:cognito-idp:ap-south-1:725755216375:userpool/ap-south-1_qhEXlobaj

  DeleteFeesType:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-institute.deleteFeesTypeHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "*"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /NTA/masters/fees/type/{id}
            Method: DELETE
          Auth:
            DefaultAuthorizer: InstituteCognitoAuthorizer
            Authorizers:
              InstituteCognitoAuthorizer:
                UserPoolArn: arn:aws:cognito-idp:ap-south-1:725755216375:userpool/ap-south-1_qhEXlobaj

  DeleteAccountsHead:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-institute.deleteAccountsHeadHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "*"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /NTA/masters/accounts/head/{id}
            Method: DELETE
          Auth:
            DefaultAuthorizer: InstituteCognitoAuthorizer
            Authorizers:
              InstituteCognitoAuthorizer:
                UserPoolArn: arn:aws:cognito-idp:ap-south-1:725755216375:userpool/ap-south-1_qhEXlobaj

  # Status Change of NTA

  StatusChangeFeesHead:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-institute.deleteFeesHeadHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "*"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /NTA/masters/fees/head/status/{id}
            Method: POST
          Auth:
            DefaultAuthorizer: InstituteCognitoAuthorizer
            Authorizers:
              InstituteCognitoAuthorizer:
                UserPoolArn: arn:aws:cognito-idp:ap-south-1:725755216375:userpool/ap-south-1_qhEXlobaj

  StatusChangeFeesType:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-institute.deleteFeesTypeHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "*"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /NTA/masters/fees/type/status/{id}
            Method: POST
          Auth:
            DefaultAuthorizer: InstituteCognitoAuthorizer
            Authorizers:
              InstituteCognitoAuthorizer:
                UserPoolArn: arn:aws:cognito-idp:ap-south-1:725755216375:userpool/ap-south-1_qhEXlobaj

  StatusChangeAccountsHead:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-institute.deleteAccountsHeadHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: "*"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /NTA/masters/accounts/head/status/{id}
            Method: POST
          Auth:
            DefaultAuthorizer: InstituteCognitoAuthorizer
            Authorizers:
              InstituteCognitoAuthorizer:
                UserPoolArn: arn:aws:cognito-idp:ap-south-1:725755216375:userpool/ap-south-1_qhEXlobaj

  # End NTA

  # Tables
  InstituteTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      TableName: InstituteTable

  TransactionsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      TableName: TransactionsTable

  StudentsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      TableName: StudentsTable

  FeesTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      TableName: FeesTable

  CourseTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      TableName: CourseTable

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
