AWSTemplateFormatVersion: 2010-09-09
Description: >-
  nta-master

Transform:
  - AWS::Serverless-2016-10-31

Resources:
  ntaInstitute:
    Type: AWS::Serverless::Application
    Properties:
      Location: 'nta-institute/template.yml'
  ntaStudent:
    Type: AWS::Serverless::Application
    Properties:
      Location: 'nta-student/template.yml'
  ntaFees:
    Type: AWS::Serverless::Application
    Properties:
      Location: 'nta-fees/template.yml'