version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "FeesCollectionApp"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1sjfj49cbeqze"
s3_prefix = "FeesCollectionApp"
region = "ap-south-1"
# confirm_changeset = true
capabilities = "CAPABILITY_IAM"
