"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.putItemHandler = exports.getByIdHandler = exports.getAllItemsHandler = void 0;
const handler_1 = require("../shared/helpers/handler");
const nta_course_handlers_service_1 = require("./nta-course.handlers.service");
const getAllItemsHandler = handler_1.AWSHandler("GET", nta_course_handlers_service_1.getAllItems);
exports.getAllItemsHandler = getAllItemsHandler;
const getByIdHandler = handler_1.AWSHandler("GET", nta_course_handlers_service_1.getById);
exports.getByIdHandler = getByIdHandler;
const putItemHandler = handler_1.AWSHandler("POST", nta_course_handlers_service_1.putItem);
exports.putItemHandler = putItemHandler;
