/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:10ead717-b95d-4c93-adb2-ed1968a59c4a",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_75LKZuJ8p",
    "aws_user_pools_web_client_id": "1494fi99h3c192bfbgtborim15",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://8yyozzk41m.execute-api.ap-south-1.amazonaws.com/dev",
            "region": "ap-south-1"
        }
    ]
};


export default awsmobile;
