version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "nta-institute"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1sjfj49cbeqze"
s3_prefix = "nta-institute"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"

