AWSTemplateFormatVersion: 2010-09-09
Description: >-
  nta-institute

Transform:
  - AWS::Serverless-2016-10-31

Globals:
  Api:
    EndpointConfiguration: REGIONAL
    Cors: "'*'"
  Function:
    Runtime: nodejs12.x
    MemorySize: 128
    Timeout: 100
    
      

Resources:
  createNTAUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/nta-institute.createNTAUserHandler
      Description: A simple example includes a HTTP post method to add one item to a DynamoDB table.
      Environment:
        Variables:
          INSTITUTE_TABLE: !Ref InstituteTable
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref InstituteTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /NTA
            Method: POST

  InstituteTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
